
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
# more details.
#
# You should have received a copy of the GNU Lesser General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#

# Include configurable nport feature makefiles
include $(NPORT_FEATURES)

# Define ALL rule.
all: config $(PROJECT_FLASH) $(PROJECT_SIZE)

clean: clean-flash clean-size config-clean

distclean: 
	$(VERBOSE)rm -rf $(DEF_BUILD_DIR)

preprocess: $(PREPROCESSED)

$(PROJECT_LIB): $(OBJECTS)

$(PROJECT_ELF): $(PROJECT_LIB)

$(PROJECT_SIZE): $(PROJECT_ELF)

$(PROJECT_FLASH): $(PROJECT_ELF)

.PHONY: test
test: all
	@./$(PROJECT_ELF)

# Include autogenerated dependency rules.
-include $(DEPENDS)
